### ISSUE TITLE
Addnodes

### ISSUE THREAD

**Issue by le2Ks** [SebastianD20/CreditCoin#1]
Hello guys, do you have any addnodes for the coin? Thx

**Comment by SebastianD20** [comment]
This is one of the main nodes. addnode 40.87.45.240 add

**Comment by le2Ks** [comment]
Hello. thank you!
Do you guys have a discord or telegram group for the project?

**Comment by SebastianD20** [comment]
Were currently working on an official Discord and Website, but here's the link so far https://discord.gg/zM4tJj7JtB
